var quotes= [
  'Agoraphilia, arousal from being outdoors in open spaces or having sex in public.',
  'Asphyxiation, arousal from being choked.',
  'Autoerotic Asphyxiation, arousal from choking themself.',
  'Autagonistophilia, arousal from being on camera or stage.',
  'Blindfolds',
  'Bondage',
  'Breath Play, controlling their partners breathing during sex.',
  'Cuckhold, arousal from seeing their partner have sex with another person.',
  'Dacryphilia, arousal from seeing someone cry.',
  'Diaper fetishism ',
  'Electric Play, playing with electricity during sex.',
  'Emetophilia, arousal from vomit.',
  'Exhibitionism, arousal from being seen in sexual situations, or being naked.',
  'Gags',
  'Hematolagnia, arousal from blood, sometimes includes licking or drinking blood.',
  'Intercrural, rubbing their penis between the other partner's thighs.',
  'Knife Play, rubbing or slightly cutting their partner with a knife during sex.',
  'Latex/Rubber, arousal from seeing their partner/being in latex/rubber.',
  'Masochism, arousal from having pain inflicted on them.',
  'Narratophilia, arousal from obscene language.',
  'Odaxelagnia, arousal from biting their partner/being bitten.',
  'Omorashi, arousal from seeing someone hold their urine. May include the actual act of wetting their pants as well.',
  'Orgasm Denial, allowing their partner to get right on the edge of orgasm and then stopping',
  'Sadism, arousal from inflicting pain on others.',
  'Sensation Play, includes all kind of sensations; blindfolds, handcuffs, putting wax on the other, feathers, anything
    that will mess with their senses.',
  'Sensory Deprivation, doing things wont allow one partner to use one or more of their senses.',
  'Spanking',
  'Stigmatophilia, arousal from body piercings and/or tattoos.',
  'Stripping/Strip Tease',
  'Stockings',
  'Suspension, arousal from being suspended in the air.',
  'Technophilia, arousal to technology.',
  'Telephonicophilia, arousal from having phone sex.',
  'Threesome/Foursome/Moresome',
  'Uniforms, arousal from being in/seeing others in uniforms. For example,
    school or military uniforms.',
  'Vincilagnia, another term for bondage. ',
  'Voyeurism, arousal from seeing other people in sexual situations.',
  'Watersports (Urophilia), arousal from urinating on others/being urinated on. (Golden Showers)',
  'Wax Play, using wax on ones partner.',
  'Weapon Fetish, arousal from weapons.',
]

function newQuote() {
  var randomNumber = Math.floor(Math.random() * (quotes.length));
  document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}
